In [15]:
import pandas as pd
import numpy as np
red_wine = pd.read_csv('/Users/cd/Documents/Code Academy Berlin/Project 2/wine+quality/winequality-red.csv', sep = ';')
red_wine_copy = red_wine.copy()
white_wine = pd.read_csv('/Users/cd/Documents/Code Academy Berlin/Project 2/wine+quality/winequality-white.csv', sep = ';')
white_wine_copy = white_wine.copy()

In [16]:
def add_underscores(red_wine):
    red_wine.columns = red_wine.columns.str.replace(' ', '_')
    return red_wine

In [17]:
red_wine = add_underscores(red_wine)

In [18]:
# we are creating a new column called "quality_label", we define a range and associate that range with a label
red_wine['quality_label'] = red_wine['quality'].apply(lambda value: 'low'
if value <= 5 else 'medium'
if value <= 7 else 'high')

In [19]:
# here we are transforming these labels into categrical data type (specific to pandas) instead of simple string
red_wine['quality_label'] = pd.Categorical(red_wine['quality_label'],
categories=['low', 'medium', 'high'])

In [20]:
def add_underscores(white_wine):
    white_wine.columns = white_wine.columns.str.replace(' ', '_')
    return white_wine

In [21]:
white_wine = add_underscores(white_wine)

In [22]:
# we are creating a new column called "quality_label", we define a range and associate that range with a label
white_wine['quality_label'] = white_wine['quality'].apply(lambda value: 'low'
if value <= 5 else 'medium'
if value <= 7 else 'high')

In [23]:
# here we are transforming these labels into categrical data type (specific to pandas) instead of simple string
white_wine['quality_label'] = pd.Categorical(white_wine['quality_label'],
categories=['low', 'medium', 'high'])

In [24]:
#here i make a column titled red_or_white in the white_wine list, and give all the white wines property 'white'

white_wine['red_or_white'] = 'white'

white_wine

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,quality_label,red_or_white
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,6,medium,white
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6,medium,white
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6,medium,white
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6,medium,white
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6,medium,white
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4893,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6,medium,white
4894,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5,low,white
4895,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6,medium,white
4896,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7,medium,white
4897,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6,medium,white

In [25]:
#here i make a column titled red_or_white in the red_wine list, and give all the red wines property 'red'


red_wine['red_or_white'] = 'red'

red_wine

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,quality_label,red_or_white
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,low,red
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,low,red
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,low,red
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,medium,red
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,low,red
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5,low,red
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6,medium,red
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6,medium,red
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5,low,red
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6,medium,red

In [26]:
combiwines = pd.concat([red_wine, white_wine], ignore_index=True)
combiwines

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,quality_label,red_or_white
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,low,red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,low,red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,low,red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,medium,red
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,low,red
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6492,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6,medium,white
6493,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5,low,white
6494,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6,medium,white
6495,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7,medium,white
6496,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6,medium,white

In [27]:
#here i create a combined data frame of the descriptions of red and white wines, and give them some keys for red wines stats and white wines stats

combined_wines_desc = pd.concat([red_wine.describe(), white_wine.describe()], axis=1, keys=["Red Wines Stats", "White Wines Stats"])
combined_wines_desc

      Red Wines Stats                                               \
        fixed_acidity volatile_acidity  citric_acid residual_sugar
count     1599.000000      1599.000000  1599.000000    1599.000000
mean         8.319637         0.527821     0.270976       2.538806
std          1.741096         0.179060     0.194801       1.409928
min          4.600000         0.120000     0.000000       0.900000
25%          7.100000         0.390000     0.090000       1.900000
50%          7.900000         0.520000     0.260000       2.200000
75%          9.200000         0.640000     0.420000       2.600000
max         15.900000         1.580000     1.000000      15.500000

                                                                          \
         chlorides free_sulfur_dioxide total_sulfur_dioxide      density
count  1599.000000         1599.000000          1599.000000  1599.000000
mean      0.087467           15.874922            46.467792     0.996747
std       0.047065           10.460157            32.895324     0.001887
min       0.012000            1.000000             6.000000     0.990070
25%       0.070000            7.000000            22.000000     0.995600
50%       0.079000           14.000000            38.000000     0.996750
75%       0.090000           21.000000            62.000000     0.997835
max       0.611000           72.000000           289.000000     1.003690

                                 ... White Wines Stats                 \
                pH    sulphates  ...       citric_acid residual_sugar
count  1599.000000  1599.000000  ...       4898.000000    4898.000000
mean      3.311113     0.658149  ...          0.334192       6.391415
std       0.154386     0.169507  ...          0.121020       5.072058
min       2.740000     0.330000  ...          0.000000       0.600000
25%       3.210000     0.550000  ...          0.270000       1.700000
50%       3.310000     0.620000  ...          0.320000       5.200000
75%       3.400000     0.730000  ...          0.390000       9.900000
max       4.010000     2.000000  ...          1.660000      65.800000

                                                                          \
         chlorides free_sulfur_dioxide total_sulfur_dioxide      density
count  4898.000000         4898.000000          4898.000000  4898.000000
mean      0.045772           35.308085           138.360657     0.994027
std       0.021848           17.007137            42.498065     0.002991
min       0.009000            2.000000             9.000000     0.987110
25%       0.036000           23.000000           108.000000     0.991723
50%       0.043000           34.000000           134.000000     0.993740
75%       0.050000           46.000000           167.000000     0.996100
max       0.346000          289.000000           440.000000     1.038980


                pH    sulphates      alcohol      quality
count  4898.000000  4898.000000  4898.000000  4898.000000
mean      3.188267     0.489847    10.514267     5.877909
std       0.151001     0.114126     1.230621     0.885639
min       2.720000     0.220000     8.000000     3.000000
25%       3.090000     0.410000     9.500000     5.000000
50%       3.180000     0.470000    10.400000     6.000000
75%       3.280000     0.550000    11.400000     6.000000
max       3.820000     1.080000    14.200000     9.000000

[8 rows x 24 columns]